import jQuery from "jquery";
import underscore from "underscore";
import TweenMax from "gsap/src/uncompressed/TweenMax";
import "scripts/shared/lib/polyfills";
import "scripts/shared/lib/tsung";
import "scripts/shared/lib/VirtualScroll";
export var $ = window.jQuery = window.$ = jQuery;
import "scripts/shared/lib/lettering";
export var _ = underscore;
export var TM = TweenMax;
